if: tag IS blank

language: java

sudo: false

jdk:
  - openjdk11

before_install:
  - wget -O jdk-linux.tar.gz $JDK_LINUX_URL
  - mkdir -p linux
  - tar -xvzf jdk-linux.tar.gz -C linux
  - wget -O jdk-mac.tar.gz $JDK_MAC_URL
  - mkdir -p mac
  - tar -xvzf jdk-mac.tar.gz -C mac
  - wget -O jdk-win.zip $JDK_WIN_URL
  - mkdir -p win
  - unzip jdk-win.zip -d win
  - pwd
  - ls -al
  - ls -al $JDK_LINUX_HOME
  - ls -al $JDK_MAC_HOME
  - ls -al $JDK_WIN_HOME

install:
  - chmod a+x ./gradlew

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch: images
  local-dir: build/image-zip
  on:
    branch: master

cache:
  directories:
  - $HOME/.gradle

script: ./gradlew --info --stacktrace runtimeZip
